import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ShopLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main className="min-h-screen bg-red-500">{children}</main>;
}
